# Linear backbone for symbolic Sudoku

num_classes: 9

backbone:
  type: config
  layers:
    - {type: linear, in_features: 9, out_features: 9}
    - {type: Softmax, dim: 1}

graph:
  type: sudoku

pairwise:
  init_scale: 0.1
